#!/bin/bash

sudo apt update -y;
sudo apt full-upgrade -y;
sudo apt install -y at python-is-python3 python3-pip python3-venv;
sudo apt autoremove -y;
python -m venv venv;
source venv/bin/activate;
pip install upgrade pip;
pip install -r requirements.txt;
deactivate;
echo "turn on SPI interface";
echo "add the following to sudo crontab";
echo "@reboot echo '~/git/pi_assistant/script' | at now + 2 minutes &> /dev/null";
