#!/bin/bash

sudo apt update -y;
sudo apt full-upgrade -y;
sudo apt install -y at python-is-python3 python3-pip python3-venv python3-dev python3-setuptools build-essential;
# pillow build dependencies
sudo apt install -y libtiff5-dev libjpeg-dev libopenjp2-7-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk libharfbuzz-dev libfribidi-dev libxcb1-dev;
sudo apt autoremove -y;
python -m venv venv;
source venv/bin/activate;
pip install --upgrade pip;
pip install wheel buildtools;
pip install -r requirements.txt;
deactivate;
echo "turn on SPI interface";
echo "add the following to sudo crontab";
echo "@reboot echo '~/git/pi-assistant/script' | at now + 2 minutes &> /dev/null";
